// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	transcript "github.com/SirNoob97/yt-transcripts/transcript"
	mock "github.com/stretchr/testify/mock"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: videoID, language
func (_m *Fetcher) Fetch(videoID string, language string) transcript.Transcript {
	ret := _m.Called(videoID, language)

	var r0 transcript.Transcript
	if rf, ok := ret.Get(0).(func(string, string) transcript.Transcript); ok {
		r0 = rf(videoID, language)
	} else {
		r0 = ret.Get(0).(transcript.Transcript)
	}

	return r0
}

// List provides a mock function with given fields: videoID
func (_m *Fetcher) List(videoID string) (map[string]string, error) {
	ret := _m.Called(videoID)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = rf(videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
